### ISSUE TITLE
How to use this example

### ISSUE THREAD

**Issue by chengjianxi** [msorvig/qt-webassembly-examples#1]
How to build this example to `.wasm` ?
Have a tutorial?

**Comment by msorvig** [comment]
Hi,  [QTBUG-63917](https://bugreports.qt.io/browse/QTBUG-63917) should contain build instructions for Qt and apps/examples.

**Comment by chengjianxi** [comment]
@msorvig 
Using the above method I compiled successed. But I encountered three questions:

1. unidentifiable Chinese code, Chinese garbled
2. page download is slow
3. Too many warnings in chrome  console, for example `untitled.js:1 bad name in getProcAddress: glUniform3uivNV,glUniform3uivNV`

Please excuse me for my poor English. Thank you so much !

**Comment by msorvig** [comment]
In reverse order:

3. This is expected, Qt attempts to resolve many/all OpenGL functions (perhaps unnecessarily), emscripten prints a warning (unlike other platforms). The warnings are harmless.

2. Is it slower than expected for a 5-10 MB download? Is https://msorvig.github.io/qt-webassembly-examples/gui_opengl/gui_opengl.html faster or equally slow? You are probably in the best position to debug this.

1. Here I don't know. Browser debug output?

**Comment by chengjianxi** [comment]
Firefox is fast than Chrome.
Download speed is same, but Chrome continue to show download page when download complete for a period of time, I do not know what it is doing. Firefox show qt page when download complete.
Close it!
