### ISSUE TITLE
Q_OS_HTML5 renamed

### ISSUE THREAD

**Issue by blockspacer** [msorvig/qt-webassembly-examples#11]
See https://bugreports.qt.io/browse/QTBUG-69168?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true

Use `defined(Q_OS_WASM) or defined(__EMSCRIPTEN__)`

Example:

```
#if defined(Q_OS_HTML5) or defined(Q_OS_WASM) or defined(__EMSCRIPTEN__)
#define PLATFORM_WASM
#endif

#ifdef PLATFORM_WASM
//...
#endif
```

**Comment by msorvig** [comment]
Removed the final Q_OS_HTML5s here now
