### ISSUE TITLE
None of the widgets work if using an adblocker

### ISSUE THREAD

**Issue by boredstiff** [msorvig/qt-webassembly-examples#3]
Chrome Version 66.0.3359.117, uBlock Origin. 

If you have these enabled, you encounter this:

![image](https://user-images.githubusercontent.com/3489076/39149832-44b05260-46f5-11e8-9ff2-640d4edb7fdb.png)

If you go to an Incognito tab, the widgets work.

Can't test Firefox, because it's managed by my facility and is too old of a version for WebAssembly.

**Comment by msorvig** [comment]
Thanks! I've seen this reported before but we did not make the adblocker connection until now:

Looks like it's spesifically blocking .wasm from github.io:

(\/proxy|\.wasm|\.wsm|\.wa)$/$xmlhttprequest,domain=github.io|rawgit.com|reactor.cc|sickrage.ca|streamplay.to|tube[REDACTED].com|vidfile.net
