### ISSUE TITLE
core_network calculated hash, and sometimes size, is wrong with em sdk 1.38.6 / qt 5.12.1, sdk 1.38.16 / qt 5.12.1, sdk 1.38.27 / qt 5.13.0-alpha

### ISSUE THREAD

**Issue by jgm-esseforma** [msorvig/qt-webassembly-examples#7]
With what versions was this hash calculated to be the same as when calculated with a Desktop build?  I'm using MacOS 10.13.6

**Comment by jgm-esseforma** [comment]
https://bugreports.qt.io/browse/QTBUG-74333

**Comment by msorvig** [comment]
See also QTBUG-74123. This was my reproducer case for that bug :)

I don't know if emscripten builds are bit-for-bit reproducible. I simply ran shasum in the terminal and compared with the output from the browser console.
